### ISSUE TITLE
[디자인] 별찍기 움직이는 애니메이션 포함해서 결과물 만들기

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#30]
## 📝 Description
**무엇을?**
- 별찍기 움직이는 애니메이션 포함해서 결과물 만들기

**왜?**
- (ex 사용자를 인증하기 위해)

## ❗️Todo
- [x] 피그마 그리기

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
별찍기 기능에 대한 시각화 - 피그마

https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=416-570&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=416%3A570&show-proto-sidebar=1
