### ISSUE TITLE
[디자인] if문 else문 디자인 구상

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#31]
## 📝 Description
**무엇을?**
-  if문 else문 디자인 구상

**왜?**
- if문 else문 시각화

## ❗️Todo
- [x] if else문 디자인, 애니메이션 생각
- [x] 시각화에 도움이 되는 디자인 고르기
- [x] 피그마 그리기

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
[if문 - 디자인](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=485-1187&t=2jgEiZd0ef79d4NV-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=485%3A1187&show-proto-sidebar=1)

[elif문 - 디자인](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=485-1810&t=2jgEiZd0ef79d4NV-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=485%3A1810&show-proto-sidebar=1)
