### ISSUE TITLE
[디자인] 리스트 자료구조 디자인

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#32]
## 📝 Description
**무엇을?**
- (ex 사용자 인증 기능)

## ❗️Todo
- [x] 리스트 자료구조 구상
- [x] 리스트 자료구조 피그마 그리기
 
## 주의할 점
- [ ] 
- [ ]

**Comment by SongGwanSeok** [comment]
<img width="818" alt="스크린샷 2024-06-21 오전 10 13 08" src="https://github.com/Co-due/SOMA/assets/105411445/6988b0da-a16d-4e82-aa66-ae09bae1d36a">


관석
[피그마 애니메이션 - 리스트 insert](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=359-251&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=359%3A251&show-proto-sidebar=1)
[피그마 애니메이션 - 리스트 remove](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=359-940&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=359%3A1247&show-proto-sidebar=1)
[피그마 애니메이션 - 리스트 expend](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=373-758&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=373%3A758&show-proto-sidebar=1)


유진
[피그마 애니메이션 - 리스트 Insert](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=358-930&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=358%3A930&show-proto-sidebar=1)

규열
[피그마 애니메이션 - 리스트 remove](https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=357-1736&t=p9G4hrZza9xCheqf-0&scaling=contain&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=357%3A1530&show-proto-sidebar=1)


Todo. 피드백 받기
