### ISSUE TITLE
[디자인] 함수 디자인 구상

### ISSUE THREAD

**Issue by SongGwanSeok** [Co-due/SOMA#38]
## 📝 Description
**무엇을?**
- 함수 디자인 구상

**왜?**
- 함수를 어떤식으로 보여줄지에 대한 고민

## ❗️Todo
- [ ] 함수를 보여주는 방식에 대한 생각
- [ ] 시각화에 도움이 되는 함수 디자인 고르기
- [ ] 피그마 그리기

## ETC
기타사항

**Comment by ujkkk** [comment]
- int()
![image](https://github.com/Co-due/SOMA/assets/88374384/a72916f2-7726-47e2-8cdd-d92f5b606992)

- max()
![image](https://github.com/Co-due/SOMA/assets/88374384/1e63d121-fa70-4805-9f93-69371b4c02f8)

- pow()
![image](https://github.com/Co-due/SOMA/assets/88374384/85e73714-f183-4608-a949-a2de610e013f)
