### ISSUE TITLE
[디자인] 구현된 별찍기 시각화에 대해 피드백

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#39]
## 📝 Description
**무엇을?**
- 구현된 별찍기 시각화에 대해 피드백

## ❗️Todo
- [x] 구현한 것 직접 써보기
- [ ] 피드백 사항 정리

## 주의할 점
- [ ] 
- [ ]

**Comment by SongGwanSeok** [comment]
피드백
https://www.notion.so/15e88b489b68443ea122cb46d85285fe
- for문 내부에서 할당 로직이 있을 때 제어문에서 확인이 안되서 불편하다.
![스크린샷 2024-06-19 오후 4 14 06](https://github.com/Co-due/SOMA/assets/105411445/903e8c36-291b-42a7-ae97-8902e39ee895)
- -> for문 내부에서 만들어서 변수에 넣는다.

**Comment by ujkkk** [comment]
피그마 애니메이션
https://www.figma.com/proto/wSQEqcewchU0o0uhQ1TVt2/Untitled?node-id=333-1510&t=ZjvRve91kHMolXPs-0&scaling=min-zoom&content-scaling=fixed&page-id=113%3A538&starting-point-node-id=333%3A1510&show-proto-sidebar=1
