### ISSUE TITLE
[Feat] AWS 아키텍처 그리기

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#41]
## 📝 Description
**무엇을?**
- draw.io로 AWS 아키텍처 그리기

**왜?**
- AWS 아키텍처 구상

## ❗️Todo
- [ ] 
- [ ] 
- [ ]

## ETC
![image](https://github.com/Co-due/gist/assets/88374384/cd89a4d1-b3eb-40b1-968d-fd31fec73395)

**Comment by SongGwanSeok** [comment]
<img width="572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1523346eb265209249368e0a111465bd79aaf312/KakaoTalk_Photo_2024-06-28-17-17-49.png" alt="KakaoTalk_Photo_2024-06-28-17-17-49.png" />
