### ISSUE TITLE
[디자인]튜플과 딕셔너리 시각화 생각

### ISSUE THREAD

**Issue by seroak** [Co-due/SOMA#66]
## 📝 Description
**무엇을?**
- 튜플과 딕셔너리 시각화 피그마로 그려보기

**왜?**
- 튜플과 딕셔너리 시각화를 하기 위해

## ❗️Todo
- [ ] 튜플 시각화 그리기
- [ ] 딕셔너리 시각화 그리기

## ETC
기타사항

**Comment by SongGwanSeok** [comment]
딕셔너리 디자인 - 관석 아이디어

<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a5aaf2a9150e810a31407290a66b1853aa4a18e/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-16%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%203.20.00.png" alt="스크린샷 2024-07-16 오후 3.20.00.png" />

**Comment by SongGwanSeok** [comment]
튜플 디자인 - 관석 아이디어

<img width="403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9nQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fec5a60daaf9a47b90649ca1760219a536f5b5db/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202024-07-16%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%203.57.09.png" alt="스크린샷 2024-07-16 오후 3.57.09.png" />
